FROM php:8.5-fpm-alpine

# Dépendances de build + extensions PHP
RUN apk add --no-cache --virtual .build-deps \
        icu-dev \
        libzip-dev \
        libpng-dev \
        oniguruma-dev \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        mysqli \
        zip \
        gd \
        mbstring \
        intl \
    && apk del .build-deps \
    && apk add --no-cache git unzip

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN mkdir -p /var/www/html && chown -R www-data:www-data /var/www/html

USER www-data

WORKDIR /var/www/html