name: Full CI process
on: [push, pull_request]
jobs:
  symfony:
    name: Symfony 8.1 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    services:
      database:
        image: mariadb:10.7.3
        env:
          MARIADB_USER: root
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: app_test
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      # —— Composer ——————————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}
            
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Security audit of dependencies
        run: composer audit

      # —— Symfony ——————————————————————————————————————————————————————————
      - name: Check Symfony requirements
        run: vendor/bin/requirements-checker

      - name: Check the Symfony console
        run: |
          bin/console about

      # —— Coding standards  ————————————————————————————————————————————————
      - name: Pphp-cs-fixer
        run: vendor/bin/php-cs-fixer fix --allow-risky=yes

      # —— Tests  ———————————————————————————————————————————————————————————

      - name: Prepare the database
        run: sudo systemctl start mysql

      - name: Run functionnal and unit tests
        run: composer app:tests
        env:
          APP_ENV: test
          DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.database.ports['3306'] }}/app_test 